// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatsForDinner.Models;

namespace WhatsForDinner.Migrations
{
    [DbContext(typeof(WhatsForDinnerContext))]
    [Migration("20220516033815_updated_models")]
    partial class updated_models
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WhatsForDinner.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("WhatsForDinner.Models.ApplicationUserWeek", b =>
                {
                    b.Property<int>("ApplicationUserWeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("BreakfastPlan")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DinnerPlan")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EverythingPlan")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LunchPlan")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RecipeWeekId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationUserWeekId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RecipeWeekId");

                    b.ToTable("ApplicationUserWeeks");
                });

            modelBuilder.Entity("WhatsForDinner.Models.BreakfastRecipe", b =>
                {
                    b.Property<int>("BreakfastRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BreakfastRecipeId1")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("BreakfastRecipeId");

                    b.HasIndex("BreakfastRecipeId1");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("BreakfastRecipes");
                });

            modelBuilder.Entity("WhatsForDinner.Models.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BreakfastRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("DinnerRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("LunchRecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DayId");

                    b.HasIndex("BreakfastRecipeId");

                    b.HasIndex("DinnerRecipeId");

                    b.HasIndex("LunchRecipeId");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("WhatsForDinner.Models.DinnerRecipe", b =>
                {
                    b.Property<int>("DinnerRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DinnerRecipeId1")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("DinnerRecipeId");

                    b.HasIndex("DinnerRecipeId1");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("DinnerRecipes");
                });

            modelBuilder.Entity("WhatsForDinner.Models.LunchRecipe", b =>
                {
                    b.Property<int>("LunchRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("LunchRecipeId1")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LunchRecipeId");

                    b.HasIndex("LunchRecipeId1");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("LunchRecipes");
                });

            modelBuilder.Entity("WhatsForDinner.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ingredients")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MaxFrequency")
                        .HasColumnType("int");

                    b.Property<int>("MinFrequency")
                        .HasColumnType("int");

                    b.Property<int?>("RecipeId1")
                        .HasColumnType("int");

                    b.Property<string>("RecipeUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<bool>("isBreakfast")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isDinner")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isLunch")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("RecipeId");

                    b.HasIndex("RecipeId1");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("WhatsForDinner.Models.RecipeDay", b =>
                {
                    b.Property<int>("RecipeDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<int?>("RecipeWeekId")
                        .HasColumnType("int");

                    b.Property<int?>("RecipeWeekId1")
                        .HasColumnType("int");

                    b.HasKey("RecipeDayId");

                    b.HasIndex("DayId");

                    b.HasIndex("RecipeWeekId");

                    b.HasIndex("RecipeWeekId1");

                    b.ToTable("RecipeDays");
                });

            modelBuilder.Entity("WhatsForDinner.Models.RecipeWeek", b =>
                {
                    b.Property<int>("RecipeWeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("WeekOf")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RecipeWeekId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("RecipeWeeks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WhatsForDinner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WhatsForDinner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatsForDinner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WhatsForDinner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WhatsForDinner.Models.ApplicationUserWeek", b =>
                {
                    b.HasOne("WhatsForDinner.Models.ApplicationUser", "User")
                        .WithMany("JoinEntities")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("WhatsForDinner.Models.RecipeWeek", "RecipeWeek")
                        .WithMany("JoinEntities")
                        .HasForeignKey("RecipeWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeWeek");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhatsForDinner.Models.BreakfastRecipe", b =>
                {
                    b.HasOne("WhatsForDinner.Models.BreakfastRecipe", null)
                        .WithMany("randomBreakfast")
                        .HasForeignKey("BreakfastRecipeId1");

                    b.HasOne("WhatsForDinner.Models.Recipe", "Recipe")
                        .WithMany("BreakfastJoinEntities")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatsForDinner.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhatsForDinner.Models.Day", b =>
                {
                    b.HasOne("WhatsForDinner.Models.BreakfastRecipe", "BreakfastRecipe")
                        .WithMany()
                        .HasForeignKey("BreakfastRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatsForDinner.Models.DinnerRecipe", "DinnerRecipe")
                        .WithMany()
                        .HasForeignKey("DinnerRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatsForDinner.Models.LunchRecipe", "LunchRecipe")
                        .WithMany()
                        .HasForeignKey("LunchRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BreakfastRecipe");

                    b.Navigation("DinnerRecipe");

                    b.Navigation("LunchRecipe");
                });

            modelBuilder.Entity("WhatsForDinner.Models.DinnerRecipe", b =>
                {
                    b.HasOne("WhatsForDinner.Models.DinnerRecipe", null)
                        .WithMany("randomDinner")
                        .HasForeignKey("DinnerRecipeId1");

                    b.HasOne("WhatsForDinner.Models.Recipe", "Recipe")
                        .WithMany("DinnerJoinEntities")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatsForDinner.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhatsForDinner.Models.LunchRecipe", b =>
                {
                    b.HasOne("WhatsForDinner.Models.LunchRecipe", null)
                        .WithMany("randomLunch")
                        .HasForeignKey("LunchRecipeId1");

                    b.HasOne("WhatsForDinner.Models.Recipe", "Recipe")
                        .WithMany("LunchJoinEntities")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatsForDinner.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhatsForDinner.Models.Recipe", b =>
                {
                    b.HasOne("WhatsForDinner.Models.Recipe", null)
                        .WithMany("WeeklyRecipes")
                        .HasForeignKey("RecipeId1");

                    b.HasOne("WhatsForDinner.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhatsForDinner.Models.RecipeDay", b =>
                {
                    b.HasOne("WhatsForDinner.Models.Day", "Day")
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatsForDinner.Models.RecipeWeek", null)
                        .WithMany("JoinEntities1")
                        .HasForeignKey("RecipeWeekId");

                    b.HasOne("WhatsForDinner.Models.RecipeWeek", null)
                        .WithMany("Week")
                        .HasForeignKey("RecipeWeekId1");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("WhatsForDinner.Models.RecipeWeek", b =>
                {
                    b.HasOne("WhatsForDinner.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WhatsForDinner.Models.ApplicationUser", b =>
                {
                    b.Navigation("JoinEntities");
                });

            modelBuilder.Entity("WhatsForDinner.Models.BreakfastRecipe", b =>
                {
                    b.Navigation("randomBreakfast");
                });

            modelBuilder.Entity("WhatsForDinner.Models.DinnerRecipe", b =>
                {
                    b.Navigation("randomDinner");
                });

            modelBuilder.Entity("WhatsForDinner.Models.LunchRecipe", b =>
                {
                    b.Navigation("randomLunch");
                });

            modelBuilder.Entity("WhatsForDinner.Models.Recipe", b =>
                {
                    b.Navigation("BreakfastJoinEntities");

                    b.Navigation("DinnerJoinEntities");

                    b.Navigation("LunchJoinEntities");

                    b.Navigation("WeeklyRecipes");
                });

            modelBuilder.Entity("WhatsForDinner.Models.RecipeWeek", b =>
                {
                    b.Navigation("JoinEntities");

                    b.Navigation("JoinEntities1");

                    b.Navigation("Week");
                });
#pragma warning restore 612, 618
        }
    }
}
